INSERT INTO article(title,content) VALUES ('가가가가','1111');
INSERT INTO article(title,content) VALUES ('나나나나','2222');
INSERT INTO article(title,content) VALUES ('다다다다','3333');
INSERT INTO article(title,content) VALUES ('당신의 인생 영화는?','댓글 고');
INSERT INTO article(title,content) VALUES ('당신의 소울 푸드는','댓글 고');
INSERT INTO article(title,content) VALUES ('당신의 취미는','댓글 고');
INSERT INTO comment(article_id,nickname,body) VALUES (4,'park','쇼생크');
INSERT INTO comment(article_id,nickname,body) VALUES (4,'kim','보헤미안');
INSERT INTO comment(article_id,nickname,body) VALUES (5,'park','치킨');
INSERT INTO comment(article_id,nickname,body) VALUES (5,'kim','수박');
INSERT INTO comment(article_id,nickname,body) VALUES (6,'park','배드민턴');
INSERT INTO comment(article_id,nickname,body) VALUES (6,'kim','클라이밍');
